#!/usr/bin/env bash

set -e

env_name=$1
if [ "$env_name" == '' ]
then
    env_name=lite
fi

if [ "$SYSTEM_DOMAIN" == '' ]
then
    SYSTEM_DOMAIN='bosh-lite.com'
fi

if [ "$CLIENT_ID" == '' ]
then
    echo ""
    echo "UAA Client ID:"
    read CLIENT_ID
fi

if [ "$CLIENT_SECRET" == '' ]
then
    echo ""
    echo "UAA Client Secret:"
    read CLIENT_SECRET
fi

if [ "$DATADOG_API_KEY" == '' ]
then
    echo ""
    echo "Datadog API Key:"
    read DATADOG_API_KEY
fi

bosh create-release --force
bosh -e $env_name upload-release --rebase
bosh -e $env_name deploy -n -d noisy-neighbor-nozzle manifests/noisy-neighbor-nozzle.yml \
    -v "uaa_client_id=$CLIENT_ID" \
    -v "uaa_client_secret=$CLIENT_SECRET" \
    -v "datadog_api_key=$DATADOG_API_KEY" \
    -v "system_domain=$SYSTEM_DOMAIN"
